source :rubygems

gem "rails", "3.0.7"
gem "rack"

gem "mysql2", "0.2.7"
gem "RedCloth", :require => "redcloth"
gem "will_paginate"
gem "formtastic"
gem "nokogiri"
gem "clearance", "~> 0.11.0"
gem "validation_reflection", ">= 0.3.6"
gem "sass"
gem "paperclip"
gem "hoptoad_notifier"
gem "copycopter_client", "~> 1.0.1"
gem "ruby-freshbooks"
gem "high_voltage"
gem "jquery-rails", "~> 1.0.11"

group :test do
  gem "capybara-webkit"
  gem "cucumber-rails"
  gem "capybara"
  gem "factory_girl_rails"
  gem "launchy"
  gem "database_cleaner"
  gem "rspec-rails", "~> 2.0.0.rc"
  gem "treetop"
  gem "sinatra"
  gem "ruby-debug"
  gem "timecop"
  gem "shoulda"
  gem "sham_rack", "1.3.1"
end
