source :gemcutter
gem "rails", "2.3.8"
gem "mysql"
gem "RedCloth"
gem "will_paginate"
gem "formtastic"
gem "nokogiri", ">= 1.4.0"
gem "clearance", ">= 0.8.8"
gem "validation_reflection", ">= 0.3.6"
gem "haml", "= 3.0.16"
gem "paperclip"
gem "hoptoad_notifier"
gem "cucumber", "0.8.5"

group :test do
  gem "cucumber-rails"
  gem "capybara"
  gem "capybara-envjs"
  gem "capybara-envjs-fixes"
  gem "johnson"
  gem "launchy"
  gem "factory_girl", "1.2.3"
  gem "database_cleaner", "0.5.0"
  gem "rspec-rails", "1.3.2"
  gem "sham_rack", "1.3.1"
  gem "polyglot", "0.3.1"
  gem "treetop", "1.4.5"
  gem "sinatra"
  gem "ruby-debug"
  gem "timecop"
end
