source :rubygems

gem "rails", "3.0.10"
gem "rack"

gem "pg"
gem "RedCloth", :require => "redcloth"
gem "will_paginate"
gem "formtastic"
gem "nokogiri"
gem "clearance", "~> 0.11.0"
gem "validation_reflection", ">= 0.3.6"
gem "sass"
gem "paperclip"
gem "hoptoad_notifier"
gem "copycopter_client", "~> 1.0.1"
gem "ruby-freshbooks"
gem "high_voltage"
gem "jquery-rails", "~> 1.0.11"
gem "heroku"
gem "acts_as_list"
gem "dynamic_form"
gem "snogmetrics"
gem "split", :git => "git://github.com/jasonm/split.git"

group :test do
  gem "headless"
  gem "cucumber-rails", "1.0.2"
  gem "capybara", "1.0.1"
  gem "factory_girl", "~> 2.0.4"
  gem "factory_girl_rails", "~> 1.1.0"
  gem "launchy"
  gem "database_cleaner"
  gem "rspec-rails", "2.6.1"
  gem "treetop"
  gem "sinatra"
  gem "ruby-debug"
  gem "timecop"
  gem "shoulda"
  gem "sham_rack", "1.3.1"
  gem "email_spec"
  gem "mocha"
end
