get "/vanity" => "vanity#index"
get "/vanity/participant/:id" => "vanity#participant"
post "/vanity/complete"
post "/vanity/chooses"
post "/vanity/reset"
post "/vanity/add_participant"
get "/vanity/image"
