development:
  adapter: active_record
  active_record_adapter: default
test:
  adapter: active_record
  active_record_adapter: default
production:
  adapter: active_record
  active_record_adapter: default
